# Generated by Django 3.0.6 on 2020-12-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='archivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('extencion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tamaño', models.IntegerField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('archivo', models.FileField(upload_to='archivos')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
            },
        ),
    ]
