# Generated by Django 3.0.6 on 2020-12-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='tamaño',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
